version: '3'

services:

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./gateway/data/nginx:/etc/nginx/conf.d
      - ./gateway/data/certbot/conf:/etc/letsencrypt
      - ./gateway/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./gateway/data/certbot/conf:/etc/letsencrypt
      - ./gateway/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
